#! /bin/bash
#
# Flywheel 2017
#
#


################################################################################
# DEFINE VARIABLES

FLYWHEEL_BASE=/flywheel/v0
MANIFEST_FILE=$FLYWHEEL_BASE/manifest.json
INPUT_DIR=$FLYWHEEL_BASE/input
GEAR_OUTPUT_DIR=$FLYWHEEL_BASE/output
WORKING_DIR=$GEAR_OUTPUT_DIR/work/
CONTAINER='[flywheel/xcpengine]'
XCP_OUTPUT_DIR=$GEAR_OUTPUT_DIR/
FMRIPREPDIR=$INPUT_DIR/fmriprepdir
IMG=$INPUT_DIR/img
M0=$INPUT_DIR/m0
STRUCT=$INPUT_DIR/antsct
DESIGNFILE=$INPUT_DIR/designfile


################################################################################
# DISPLAY XCPENGINE DOCKERFILE FOR BUILD INFO

echo -e "$CONTAINER BEGIN XCPENGINE DOCKERFILE\n"
cat ${FLYWHEEL_BASE}/*Dockerfile
echo -e "$CONTAINER END XCPENGINE DOCKERFILE \n"


################################################################################
# CONFIGURE ENV

source ${FLYWHEEL_BASE}/docker-env.sh


##############################################################################
# Parse configuration

   # get the inputs files

if [[ -f $CONFIG_FILE ]]; then
  eval $(jq -r '.inputs | to_entries[] | "XCP_INPUT_\(.key)=\(.value.location.path)"' $CONFIG_FILE)
  echo "$(set | grep FW_INPUT)"
fi



function parse_config {

  CONFIG_FILE=$FLYWHEEL_BASE/config.json
  MANIFEST_FILE=$FLYWHEEL_BASE/manifest.json

  if [[ -f $CONFIG_FILE ]]; then
    echo "$(cat $CONFIG_FILE | jq -r '.config.'$1)"
  else
    CONFIG_FILE=$MANIFEST_FILE
    echo "$(cat $MANIFEST_FILE | jq -r '.config.'$1'.default')"
  fi
}

analysis_type="$(parse_config 'analysis_type')"
task_name="$(parse_config 'task_name')"

# task name to be work on 

################################################################################

# check the design file

if [[ -z "${DESIGNFILE}/*dsn" ]]; then
    echo -e "The design file is not supply or not available  \n!"
    echo -e " SEE https://xcpengine.readthedocs.io/config/design.html#designfile \n "
    exit 1
fi
cohortfile=${XCP_OUTPUT_DIR}/cohortfile.csv

# check fmriprep directory
if [[ $FMRIPREPDIR/*zip ]]; then 
  echo "FMRIPREP output is zip file and will be unzipped"
  fmriprepout=$(ls -f $FMRIPREPDIR/*zip)
  mkdir -p $XCP_OUTPUT_DIR/fmriprep
  unzip -q ${fmriprepout} -d $XCP_OUTPUT_DIR/fmriprep
  rm -rf ${cohortfile}  
  echo id0,id1,id2,id3,img > ${cohortfile} # 3 ids for now 
  im=$(ls -f $XCP_OUTPUT_DIR/fmriprep/*/fmriprep/sub-*/ses-*/func/*desc-preproc_bold.nii.gz)
  base1=$(basename $(ls -d $XCP_OUTPUT_DIR/fmriprep/*/fmriprep/sub-*))
  base2=$(basename $(ls -d $XCP_OUTPUT_DIR/fmriprep/*/fmriprep/sub-*/ses-*))
     for i in  $im
         do
         id0=$(echo $i |cut -d'_' -f3)
         id1=$(echo $i |cut -d'_' -f4)
         echo $base1,$base2,$id0,$id1,$i >> $cohortfile
      done
fi


if  [[ -f $(ls -f ${IMG}/*nii.gz) ]]; then 
      img=$(ls -f ${IMG}/*nii.gz)
      echo " Ensure appropriate design file is supplied \n"
      anatdir=$(ls -d $XCP_OUTPUT_DIR/fmriprep/*/fmriprep/sub-*/anat/)
      if [[ -d ${anatdir} ]]; then 
      rm -rf ${cohortfile}
      echo "\n"
      echo id0,img,anatdir > $cohortfile
      echo sub,${img},${anatdir} >> $cohortfile  
              if [[ -f $(ls -f ${M0}/*nii.gz) ]]; then
                  m0=$(ls -f ${M0}/*nii.gz )
                  rm -rf ${cohortfile}
                  echo id0,img,anatdir,m0 > $cohortfile
                  echo sub,${mg},${anatdir},${m0}>> $cohortfile 
              fi
      elif [[ -f $(ls -f ${STRUCT}/*zip ) ]]; then 
        rm -rf ${cohortfile}
         anat=$(ls -f ${STRUCT}/*zip)
          unzip  -q ${anat} -d $XCP_OUTPUT_DIR/antsct
          antsctdir=$(ls -d $XCP_OUTPUT_DIR/antsct/xcpengine/*/struc)
          echo id0,img,antsct > $cohortfile
          echo sub,${img},${antsctdir} >> $cohortfile
            if [[ -f $(ls -f ${M0}/*nii.gz) ]]; then
                  m0=$(ls -f ${M0}/*nii.gz )
                  rm -rf ${cohortfile}
                  echo id0,img,antsct > $cohortfile
                  echo sub,${img},${antsctdir} >> $cohortfile
            fi
      else 
       rm -rf ${cohortfile}
       echo id0,img,antsct > $cohortfile
       echo sub,${img},${antsctdir} >> $cohortfile
      fi
fi

################################################################################
# RUN XCPEENGINE now
designfile=$(ls -f $DESIGNFILE/*dsn)
time /xcpEngine/xcpEngine \
      -d  $designfile  \
      -c  $cohortfile  \
      -o  ${XCP_OUTPUT_DIR}/xcpengine \
      -i  ${WORKING_DIR}

rm -rf $XCP_OUTPUT_DIR/fmriprep
cd  $XCP_OUTPUT_DIR/ 
zip -r -q ${XCP_OUTPUT_DIR}/xcpEngineouput_${analysis_type}.zip xcpengine
rm -rf $XCP_OUTPUT_DIR/xcpengine


XCPENGINE_EXITSTATUS=$?


################################################################################
# CLEANUP OUTPUTS


echo "$CONTAINER  completed the execution. Check the log files for anyg errors."
echo ' '
echo ' cleaning the working directory'
cd "$GEAR_OUTPUT_DIR"

  chmod -R 777 $GEAR_OUTPUT_DIR


# Clean up
rm -rf "$WORKING_DIR"

exit XCPENGINE_EXITSTATUS
